name: Program Runner

on:
  push:
    branches:
      - main

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t $GITHUB_REPOSITORY .

      - name: Run Docker container
        run: docker run --rm $GITHUB_REPOSITORY